name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.9.8+2
homepage: https://github.com/brianegan/chewie
authors:
  - Brian Egan <brian@brianegan.com>
  - Ben Hagen <ben@ottomatic.io>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  open_iconic_flutter: ">=0.3.0 <10.4.0"
  videoplayer:
    git:
      url: https://github.com/waitwalker/video_player_flutter_2.git
      ref: 'main'
  wakelock: ^0.5.0+2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
